"""columns user xp boost

Revision ID: 66af86144c4a
Revises: d047776078cc
Create Date: 2026-06-14 17:52:19.583078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66af86144c4a'
down_revision = 'd047776078cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_multiplier', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('xp_boost_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('xp_boost_until')
        batch_op.drop_column('xp_multiplier')

    # ### end Alembic commands ###
