"""add item fields

Revision ID: 7006799060ed
Revises: 
Create Date: 2026-06-08 11:56:54.145163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7006799060ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('icon', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_stackable', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_items', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('is_stackable')
        batch_op.drop_column('icon')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
