"""equip slots

Revision ID: d047776078cc
Revises: 7006799060ed
Create Date: 2026-06-14 14:27:16.965831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd047776078cc'
down_revision = '7006799060ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipped_frame_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipped_avatar_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipped_title_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'item', ['equipped_title_id'], ['id'])
        batch_op.create_foreign_key(None, 'item', ['equipped_frame_id'], ['id'])
        batch_op.create_foreign_key(None, 'item', ['equipped_avatar_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipped_title_id')
        batch_op.drop_column('equipped_avatar_id')
        batch_op.drop_column('equipped_frame_id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
